### PR TITLE
Convert docs to asciidoc/antora

### PR DESCRIPTION
**Pull request by pvlugter**

### CODE REVIEW

**Comment by pvlugter** [comment]
Tests are failing, because the latest proxy is used and stateless function was renamed to action. Looks like the latest version was used for other updates (around error handling?) so using `0.5.1` also won't work. I can publish an in-between snapshot version of the proxy, before the action rename, to get this working.

**Comment by sleipnir** [comment]
@pvlugter What does it take to rename yourself to Action permanently?

**Comment by pvlugter** [comment]
Renaming to `Action` is just renames, with the same behaviour, so should be straightforward. I'll merge this simple doc conversion, and we can follow up on the action rename.

**Comment by pvlugter** [comment]
Published: https://cloudstate.io/docs/python/

**Comment by owlet-labs** [comment]
I have most of an implementation for renaming to action. Latest tck is working. Have a few things to finish--hopefully will get it finished in the next week or so.

**Comment by marcellanz** [comment]
@GratefulTony awesome, great news.

**Comment by pvlugter** [comment]
@GratefulTony awesome. There are also some TCK tests for Actions added here https://github.com/cloudstateio/cloudstate/pull/468

**Pull request merged**
